MOVIE_GENRE_NONE = 0
MOVIE_GENRE_ADVENTURE = 1
MOVIE_GENRE_ACTION = 2
MOVIE_GENRE_ANIMATION = 3
MOVIE_GENRE_DRAMA = 4
MOVIE_GENRE_SCI_FI = 5
MOVIE_GENRE_FANTASY = 6
MOVIE_GENRE_HORROR = 7
MOVIE_GENRE_MYSTERY = 8
MOVIE_GENRE_THRILLER = 9
MOVIE_GENRE_WAR = 10
MOVIE_GENRE_FAMILY = 11
MOVIE_GENRE_MUSICAL = 12
MOVIE_GENRE_ROMANCE = 13
MOVIE_GENRE_CRIME = 14
MOVIE_GENRE_HISTORY = 15
MOVIE_GENRE_WESTERN = 16
MOVIE_GENRE_FILM_NOIR = 17
MOVIE_GENRE_DOCUMENTARY = 18
MOVIE_GENRE_COMEDY = 19
MOVIE_GENRE_SHORT = 20
MOVIE_GENRE_SPORT = 21
MOVIE_GENRE_TALK_SHOW = 22
MOVIE_GENRE_BIOGRAPHY = 23
MOVIE_GENRE_NEWS = 24
MOVIE_GENRE_REALITY_TV = 25
MOVIE_GENRE_GAME_SHOW = 26
MOVIE_GENRE_MUSIC = 27

MOVIES_GENRE = (
    (MOVIE_GENRE_NONE, 'NONE'),
    (MOVIE_GENRE_ADVENTURE, 'Adventure'),
    (MOVIE_GENRE_ACTION, 'Action'),
    (MOVIE_GENRE_ANIMATION, 'Animation'),
    (MOVIE_GENRE_DRAMA, 'Drama'),
    (MOVIE_GENRE_SCI_FI, 'Sci-Fi'),
    (MOVIE_GENRE_FANTASY, 'Fantasy'),
    (MOVIE_GENRE_HORROR, 'Horror'),
    (MOVIE_GENRE_MYSTERY, 'Mystery'),
    (MOVIE_GENRE_THRILLER, 'Thriller'),
    (MOVIE_GENRE_WAR, 'War'),
    (MOVIE_GENRE_FAMILY, 'Family'),
    (MOVIE_GENRE_MUSICAL, 'Musical'),
    (MOVIE_GENRE_ROMANCE, 'Romance'),
    (MOVIE_GENRE_CRIME, 'Crime'),
    (MOVIE_GENRE_HISTORY, 'History'),
    (MOVIE_GENRE_WESTERN, 'Western'),
    (MOVIE_GENRE_FILM_NOIR, 'Film-Noir'),
    (MOVIE_GENRE_DOCUMENTARY, 'Documentary'),
    (MOVIE_GENRE_COMEDY, 'Comedy'),
    (MOVIE_GENRE_SHORT, 'Short'),
    (MOVIE_GENRE_SPORT, 'Sport'),
    (MOVIE_GENRE_TALK_SHOW, 'Talk-Show'),
    (MOVIE_GENRE_BIOGRAPHY, 'Biography'),
    (MOVIE_GENRE_NEWS, 'News'),
    (MOVIE_GENRE_REALITY_TV, 'Reality-TV'),
    (MOVIE_GENRE_GAME_SHOW, 'Game-Show'),
    (MOVIE_GENRE_MUSIC, 'Music')
)
