# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('m_id', models.AutoField(db_column=b'm_id', primary_key=True, serialize=False)),
                ('m_title', models.TextField(db_column=b'm_title', default=b'')),
                ('m_director', models.TextField(db_column=b'm_director', default=b'')),
                ('m_genre', models.TextField(db_column=b'm_genre', default=b'')),
                ('m_imdb_score', models.DecimalField(decimal_places=1, default=b'', max_digits=50)),
                ('m_99popularity', models.DecimalField(decimal_places=1, default=b'', max_digits=50)),
            ],
        ),
    ]
