# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('m_id', models.AutoField(db_column=b'm_id', primary_key=True, serialize=False)),
                ('m_title', models.TextField(db_column=b'm_title', default=b'')),
                ('m_director', multiselectfield.db.fields.MultiSelectField(db_column=b'm_director', default=b'', max_length=200)),
                ('m_genre', models.TextField(choices=[(0, b'NONE'), (1, b'Adventure'), (2, b'Action'), (3, b'Animation'), (4, b'Drama'), (5, b'Sci-Fi'), (6, b'Fantasy'), (7, b'Horror'), (8, b'Mystery'), (9, b'Thriller'), (10, b'War'), (11, b'Family'), (12, b'Musical'), (13, b'Romance'), (14, b'Crime'), (15, b'History'), (16, b'Western'), (17, b'Film-Noir'), (18, b'Documentary'), (19, b'Comedy'), (20, b'Short'), (21, b'Sport'), (22, b'Talk-Show'), (23, b'Biography'), (24, b'News'), (25, b'Reality-TV'), (26, b'Game-Show'), (27, b'Music')])),
                ('m_imdb_score', models.PositiveIntegerField(db_column=b'm_imdb_score', default=b'')),
                ('m_99popularity', models.PositiveIntegerField(db_column=b'm_99popularity', default=b'')),
            ],
        ),
    ]
